---
- include: users_and_groups.yml

- shell: ls -la {{ jetty_dst_dir }}/current
  register: jetty_current
  ignore_errors: yes
  tags: jetty

- set_fact:
    jetty_required: false
  tags: jetty

- set_fact:
    jetty_required: true
  when: jetty_current.stdout.find("jetty-distribution-{{ jetty_version }}") == -1
  tags: jetty

- include: install_new.yml
  when: jetty_required

- name: Create symbolic link to logs
  file:
    src="{{ jetty_dst_dir }}/current/logs"
    dest=/var/log/jetty
    state=link
  tags: jetty

- name: Update the init script stop process timeout
  replace: dest="{{ jetty_dst_dir }}/current/bin/jetty.sh" regexp='TIMEOUT=(\d+)$' replace='TIMEOUT={{ jetty_stop_timeout }}' backup=yes
  tags: jetty

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Create default configuration file
  template:
    src=default-jetty.j2
    dest=/etc/default/jetty
    owner=root
    group=root
    mode=0644
  tags: jetty

- name: start the service
  service: name=jetty enabled=yes state=started
