---
- name: install init.d script
  file:
    src="{{ jetty_dst_dir }}/current/bin/jetty.sh"
    dest=/etc/init.d/jetty
    state=link
  when: ansible_distribution_major_version == '6'
  tags: jetty

- name: install systemd script
  template: src="jetty.service.j2" dest="/etc/systemd/system/jetty.service"
  when: ansible_distribution_major_version == '7'
  tags: jetty

- name: reload systemd units
  command: systemctl daemon-reload
  when: ansible_distribution_major_version == '7'
  tags: jetty
